<?php

namespace App\Http\Requests\Household;

use Illuminate\Foundation\Http\FormRequest;

class UpdateHouseholdRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'name' => 'sometimes|string|max:255',
            'manual_balance' => 'sometimes|numeric',
            'budget_enabled' => 'sometimes|boolean',
            'savings_enabled' => 'sometimes|boolean',
            'debts_enabled' => 'sometimes|boolean',
            'utilities_enabled' => 'sometimes|boolean',
            'meters_enabled' => 'sometimes|boolean',
            'onboarding_completed' => 'sometimes|boolean',
            'business_enabled' => 'sometimes|boolean',
            'business_name' => 'sometimes|string|max:255',
            'shopify_import_enabled' => 'sometimes|boolean',
            'shopify_shop_url' => 'sometimes|nullable|string|max:255',
            'shopify_access_token' => 'sometimes|nullable|string|max:4096',
            'woocommerce_import_enabled' => 'sometimes|boolean',
            'woocommerce_shop_url' => 'sometimes|nullable|string|max:255',
            'woocommerce_consumer_key' => 'sometimes|nullable|string|max:4096',
            'woocommerce_consumer_secret' => 'sometimes|nullable|string|max:4096',
            'unas_import_enabled' => 'sometimes|boolean',
            'unas_shop_id' => 'sometimes|nullable|string|max:255',
            'unas_api_key' => 'sometimes|nullable|string|max:4096',
            'sumup_import_enabled' => 'sometimes|boolean',
            'sumup_merchant_code' => 'sometimes|nullable|string|max:32',
            'sumup_api_key' => 'sometimes|nullable|string|max:4096',
            'pocket_money_enabled' => 'sometimes|boolean',
            'insurance_enabled' => 'sometimes|boolean',
            'rental_enabled' => 'sometimes|boolean',
            'receivables_enabled' => 'sometimes|boolean',
            'travel_planner_enabled' => 'sometimes|boolean',
            'utility_split_enabled' => 'sometimes|boolean',
            'utility_split_partner_id' => 'sometimes|nullable|integer|exists:users,id',
            'business_settings' => 'sometimes|array',
            'business_settings.channels' => 'sometimes|array',
            'business_settings.channels.*' => 'string|max:100',
            'business_settings.payment_methods' => 'sometimes|array',
            'business_settings.payment_methods.*' => 'string|max:100',
            'business_settings.providers' => 'sometimes|array',
            'business_settings.providers.*' => 'string|max:100',
            'business_settings.destinations' => 'sometimes|array',
            'business_settings.destinations.*' => 'string|max:100',
            'business_settings.default_vat_percent' => 'sometimes|numeric|min:0|max:100',
            'business_settings.price_input_mode' => 'sometimes|in:net,gross',
            'business_settings.order_statuses' => 'sometimes|array',
            'business_settings.order_statuses.*' => 'string|max:100',
            'business_settings.order_status_colors' => 'sometimes|array',
            'business_settings.order_status_colors.*' => 'string|in:success,warning,danger,info,primary,neutral',
            'business_settings.shopify_sync_schedule' => 'sometimes|in:off,hourly,every_6_hours,daily',
            'business_settings.tax_regime' => 'sometimes|in:aam,vat,kata',
            'business_settings.income_tax_method' => 'sometimes|in:cost_ratio,actual,kata_flat',
            'business_settings.cost_ratio_percent' => 'sometimes|numeric|min:0|max:100',
            'business_settings.revenue_basis' => 'sometimes|in:documented_only,all_orders',
            'budget_settings.default_currency' => 'sometimes|in:HUF,EUR,USD',
            'utility_templates' => 'sometimes|array',
            'utility_templates.*.type' => 'required|string|max:100',
            'utility_templates.*.total' => 'sometimes|numeric|min:0',
            'utility_templates.*.due_day' => 'sometimes|integer|min:1|max:28',
            'utility_templates.*.split_rule' => 'sometimes|in:shared,dani-private,ildi-private',
            'savings_settings' => 'sometimes|array',
            'savings_settings.owners' => 'sometimes|array',
            'savings_settings.owners.*' => 'string|max:100',
            'savings_settings.default_owner' => 'sometimes|nullable|string|max:100',
            'savings_settings.separate_owner' => 'sometimes|nullable|string|max:100',
            'savings_settings.currencies' => 'sometimes|array',
            'savings_settings.currencies.*' => 'string|max:10',
            'savings_settings.default_count_in_savings' => 'sometimes|boolean',
            'debts_settings' => 'sometimes|array',
            'debts_settings.default_strategy' => 'sometimes|in:avalanche,snowball',
            'debts_settings.default_extra_monthly' => 'sometimes|integer|min:0',
            'debts_settings.pay_add_to_budget_default' => 'sometimes|boolean',
            'debts_settings.payment_category_pattern' => 'sometimes|string|max:100',
            'debts_settings.reminder_days_before' => 'sometimes|integer|min:0|max:60',
            'debts_settings.default_interest_rate_annual' => 'sometimes|numeric|min:0|max:100',
            'debts_settings.debt_type_templates' => 'sometimes|array',
            'debts_settings.debt_type_templates.*.label' => 'required|string|max:100',
            'debts_settings.debt_type_templates.*.default_interest_rate_annual' => 'sometimes|numeric|min:0|max:100',
            'pocket_money_settings' => 'sometimes|array',
            'pocket_money_settings.currencies' => 'sometimes|array|min:1',
            'pocket_money_settings.currencies.*' => 'string|max:8',
            'pocket_money_settings.default_currency' => 'sometimes|string|max:8',
            'pocket_money_settings.members' => 'sometimes|array',
            'pocket_money_settings.members.*.id' => 'required|string|max:64',
            'pocket_money_settings.members.*.label' => 'required|string|max:100',
            'pocket_money_settings.members.*.member_user_id' => 'nullable|integer|exists:users,id',
            'pocket_money_settings.members.*.icon' => 'required|string|max:32',
            'pocket_money_settings.members.*.sticker_color' => 'nullable|string|regex:/^#[0-9A-Fa-f]{6}$/',
            'pocket_money_settings.members.*.icon_color' => 'nullable|string|regex:/^#[0-9A-Fa-f]{6}$/',
            'pocket_money_settings.hidden_member_keys' => 'sometimes|array',
            'pocket_money_settings.hidden_member_keys.*' => 'string|max:128',
            'pocket_money_settings.interest_enabled' => 'sometimes|boolean',
            'pocket_money_settings.interest_rate_percent' => 'sometimes|numeric|min:0|max:100',
            'pocket_money_settings.interest_on' => 'sometimes|in:balance,month_allowance',
            'pocket_money_settings.interest_basis' => 'sometimes|in:no_expense,remaining',
            'insurance_settings' => 'sometimes|array',
            'insurance_settings.reminder_days_before' => 'sometimes|integer|min:1|max:365',
            'insurance_settings.currencies' => 'sometimes|array|min:1',
            'insurance_settings.currencies.*' => 'string|max:8',
            'insurance_settings.default_currency' => 'sometimes|string|max:8',
            'insurance_settings.payment_category_pattern' => 'sometimes|string|max:64',
            'insurance_settings.budget_sync_default' => 'sometimes|boolean',
            'rental_settings' => 'sometimes|array',
            'rental_settings.currencies' => 'sometimes|array|min:1',
            'rental_settings.currencies.*' => 'string|max:8',
            'rental_settings.default_currency' => 'sometimes|string|max:8',
            'rental_settings.contract_reminder_days_before' => 'sometimes|integer|min:1|max:365',
            'budget_settings' => 'sometimes|array',
            'budget_settings.clone_mode' => 'sometimes|in:all,budget_only,fixed_recurring',
            'budget_settings.missed_income_enabled' => 'sometimes|boolean',
            'budget_settings.missed_income_grace_days' => 'sometimes|integer|min:0|max:60',
            'budget_settings.category_groups' => 'sometimes|array',
            'budget_settings.category_groups.*.name' => 'required|string|max:100',
            'budget_settings.category_groups.*.color' => 'sometimes|string|max:7',
            'budget_settings.category_groups.*.categories' => 'sometimes|array',
            'budget_settings.category_groups.*.categories.*' => 'string|max:100',
            'budget_settings.category_colors' => 'sometimes|array',
            'budget_settings.category_colors.*' => 'string|max:7',
            'utilities_settings' => 'sometimes|array',
            'utilities_settings.clone_from_previous_month' => 'sometimes|boolean',
            'utilities_settings.settlement_auto_suggest' => 'sometimes|boolean',
            'utilities_settings.default_payer_user_id' => 'sometimes|nullable|integer',
            'dashboard_settings' => 'sometimes|array',
            'dashboard_settings.widget_order' => 'sometimes|array',
            'dashboard_settings.widget_order.*' => 'in:alerts,ai_cfo,primary_metrics,secondary_metrics,main_grid,business_chart,ai_briefing',
            'utility_templates.*.provider' => 'sometimes|nullable|string|max:100',
            'utility_templates.*.payment_method' => 'sometimes|nullable|string|max:100',
            'utility_templates.*.budget_category' => 'sometimes|nullable|string|max:100',
            'meters_settings' => 'sometimes|array',
            'meters_settings.default_location' => 'sometimes|string|max:100',
            'meters_settings.units' => 'sometimes|array|min:1',
            'meters_settings.units.*' => 'string|max:20',
            'meters_settings.templates' => 'sometimes|array',
            'meters_settings.templates.*.name' => 'required|string|max:100',
            'meters_settings.templates.*.unit' => 'sometimes|string|max:20',
            'meters_settings.templates.*.location' => 'sometimes|string|max:100',
            'meters_settings.reading_reminder_day' => 'sometimes|integer|min:0|max:28',
            'meters_settings.consumption_alert_percent' => 'sometimes|integer|min:0|max:200',
            'meters_settings.show_annual_summary_on_dashboard' => 'sometimes|boolean',
            'meters_settings.location_groups' => 'sometimes|array',
            'meters_settings.location_groups.*.name' => 'required|string|max:100',
            'meters_settings.location_groups.*.locations' => 'sometimes|array',
            'meters_settings.location_groups.*.locations.*' => 'string|max:100',
        ];
    }
}
