# fly.toml app configuration file generated for osszhang-backend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'osszhang-backend'
primary_region = 'fra'
console_command = 'php /var/www/artisan tinker'

[build]
  dockerfile = "Dockerfile"
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_ENV = 'production'
  FRONTEND_URL = 'https://osszhang.vercel.app'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "sh -c 'php /var/www/artisan migrate --force && php /var/www/artisan demo:seed'"
